---
title: "Untitled"
author: "Aaron Owen"
date: "11/10/2017"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
lasso = read.csv("top40_coeffs_lasso.csv")
enet = read.csv("top40_coeffs_Enet.csv")
boost = read.csv("top40_coeffs_GBoost.csv")
lboost = read.csv("top40_coeffs_LGBoost.csv")
```

```{r}
lasso$color = ifelse(lasso$Coeff > 0, "pos", "neg")
enet$color = ifelse(enet$Coeff > 0, "pos", "neg")
```

```{r}
lasso$features = c(
    "Commercial Zone", "Abnormal Sale", "Medium Density Zone", "Conventional Sale; Fair House", "Heating Quality",
    "Conventional Deed", "Basement Quality", "Kitchen Quality", "Townhouse", "Kitchens Above Ground",
    "Exterior Quality", "Wood Siding", "Year Sold", "Good Basement Quality and Typical Condition", "Edwards Neighborhood",
    "Basement Exposure", "Basement Finished Type1", "Garage Finish Type", "Hard Board Exterior", "Close to Arterial Street",
    "Full Basement Bathrooms", "Num Fireplaces", "BrkSide Neighborhood", "Cul-de-sac", "1 Family Hoouse",
    "Num Car Garage", "Year Remodeled", "Concrete Foundation", "StoneBr Neighborhood", "New Sale",
    "Close to City Conditions", "Brick Exterior", "Overall Condition", "Central Air", "Finished Basement Area1",
    "Crawford Neighborhood", "Year Built", "Overall Area", "Above Ground Area", "Overall Quality"
)

ggplot(lasso, aes(x = reorder(features, Coeff), y = Coeff)) + 
    geom_bar(aes(fill = color), stat = "identity", show.legend = F) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), 
          plot.title = element_text(hjust = 0.5),
          axis.text = element_text(size = 10)) +
    ylim(c(-0.25, 0.25)) +
    labs(y = "Coefficients", x = " ", title = "Coefficients of Top 40 Predictors")
```

```{r}
enet$features = c(
    "Commercial Zone", "Conventional Sale; Fair House", "Medium Density Zone", "Gravity Furance", "Abnormal Sale",
    "MeadowV Neighborhood", "Conventional Deed", "Kitchens Above Ground", "December 2009", "Townhouse",
    "September 2007", "Court Deed", "Heating Quality", "April 2009", "February 2007",
    "Close to Arterial Street", "Edwards Neighborhood", "Basement Quality", "October 2008", "Mitchel Neighborhood",
    "1 Family House", "Full Basement Bathrooms", "Num Car Garage", "Concrete Foundation", "Year Remodeled",
    "Close to City Conditions", "Somerset Neighborhood", "Nridgeht Neighborhood", "Cul-de-sac", "Overall Condition",
    "BrkSide Neighborhood", "Central Air", "Basement Finished Area1", "Brick Exterior", "StoneBr Neighborhood",
    "Year Built", "Total Area", "Crawford Neighborhood", "Overall Quality", "Above Ground Area"
)

ggplot(enet, aes(x = reorder(features, Coeff), y = Coeff)) + 
    geom_bar(aes(fill = color), stat = "identity", show.legend = F) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), 
          plot.title = element_text(hjust = 0.5),
          axis.text = element_text(size = 10)) +
    ylim(c(-0.3, 0.3)) +
    labs(y = "Coefficients", x = " ", title = "Coefficients of Top 40 Predictors")
```

```{r}
boost$features = c(
    "Lot Area", "Above Ground Area", "1st Floor Area", "Overall Area", "Unfinished Basement Area",
    "Total Basement Area", "Lot Frontage", "Garage Area", "Year Built", "Finished Basement Area1",
    "Open Porch Area", "Year Remodeled", "Garage Year Built", "2nd Floor Area", "Wood Deck Area",
    "Masonry Veneer Area", "Month Sold", "Enclosed Porch", "Overall Quality", "Year Sold",
    "Overall Condition", "Rooms Above Ground", "Basement Finish Type1", "Bedrooms Above Ground", "House Type",
    "Num Fireplaces", "Screen Porch Area", "Kitchen Quality", "Finished Basement Area2", "Lot Shape",
    "Basement Exposure", "Fireplace Quality", "Garage Finish", "Heating Quality", "Full Basement Bathrooms",
    "Fence", "Basement Quality", "Home Functional", "Finished Basement Type2", "Exterior Quality")

ggplot(boost, aes(x = reorder(features, Importance), y = Importance)) + 
    geom_bar(stat = "identity", color = "black", fill = "lightblue") + 
    coord_flip() + 
    theme(plot.title = element_text(hjust = 0.5),
          axis.text = element_text(size = 10),
          axis.title.y = element_blank()) +
    ggtitle("RTop 40 Features by Relative Importance")
```

```{r}
lboost$features = c(
    "Above Ground Area", "Lota Area", "Overall Area", "Overall Condition", "Overall Quality",
    "Year Built", "Garage Year Built", "1st Floor Area", "Garage Area", "Finished Basement Area1",
    "Lot Frontage", "Home Functional", "Exterior Quality", "Unfinished Basement Area", "Total Basement Area",
    "Year Remodeled", "Brick Exterior", "Enclosed Porch Area", "Open Porch Area", "StoneBr Neighborhood",
    "2nd Floor Area", "Basement Finish Type1", "Num Fireplaces", "Full Basement Bathrooms", "Brk Neighborhood",
    "House Type", "Detached Garage", "Fireplace Quality", "Crawford Neighborhood", "Bathrroms Above Ground",
    "Wood Deck Area", "Typical Exterior and Condition", "Abnormal Sale", "Basement Exposure", "Year Sold",
    "Month Sold", "Screen Porch Area", "Somerset Neighborhood", "Above Ground Kitchens", "Fair Condition; Conventional Deed")

ggplot(lboost, aes(x = reorder(features, Importance), y = Importance)) + 
    geom_bar(stat = "identity", color = "black", fill = "lightblue") + 
    coord_flip() +
        theme(plot.title = element_text(hjust = 0.5),
          axis.text = element_text(size = 10),
          axis.title.y = element_blank()) +
    ggtitle("Top 40 Features by Relative Importance")
```

```{r}
forest = read.csv("top40_coeffs_forest.csv")
```

```{r}
forest$features = c(
    "Overall Area", "Overall Quality", "Above Ground Area", "Year Built", "Garage Area",
    "Total Basement Area", "Year Garage Built", "Num Car Garage", "1st Floor Area", "Exterior Quality",
    "Year Remodeled", "Basement Quality", "Num Full Baths", "Kitchen Quality", "Num Fireplaces",
    "Concrete Foundation", "Lot Area", "Rooms Above Ground", "Finished Basement Area1", "2nd Floor Area",
    "Good and Typical Exterior", "Open Porch Area", "Excellent and Typical Basement", "Typical Exterior", "Lot Frontage",
    "Heating Quality", "Garage Finish", "Masonry Veneer Area", "Attached Garage", "Typical Basement",
    "Central Air", "Garage Condition", "Fireplace Quality", "Detached Garage", "House Type",
    "Overall Condition", "Num Half Bathrooms", "Wood Deck Area", "Bedrooms Above Ground", "Medium Density Zone"
)

ggplot(forest, aes(x = reorder(features, Importance), y = Importance)) + 
    geom_bar(stat = "identity", color = "black", fill = "lightblue") + 
    coord_flip() +
        theme(plot.title = element_text(hjust = 0.5),
          axis.text = element_text(size = 10),
          axis.title.y = element_blank()) +
    ggtitle("Top 40 Features by Relative Importance")
```

```{r}
train = read.csv("train.csv")
```

```{r}
sd(train$SalePrice)*.1071
```

```{r}
summary(train$SalePrice)
```

```{r}
sd(train$SalePrice)*.1071/median(train$SalePrice)
sd(train$SalePrice)*.1071/min(train$SalePrice)
sd(train$SalePrice)*.1071/max(train$SalePrice)
```

